name: Build and deploy Node.js app to Azure Web App - ExpenserPro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # or your Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: ./xpenserpro-server # path to folder with package.json

      - name: Build project
        run: npm run build
        working-directory: ./xpenserpro-server

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./xpenserpro-server # path to built server folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C36CA415C6EE4F849972CB9E64DEB6BF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6EFC08BD42B947788F497158224E5929 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9093AA496F4E4C93AE067780F909D833 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ExpenserPro'
          slot-name: 'Production'
          package: .
